# fly.toml app configuration file generated for shopsmart on 2023-06-22T21:08:41-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shopsmart"
primary_region = "gdl"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
